# Generated by Django 5.1.2 on 2024-10-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
