# Generated by Django 5.1.2 on 2024-10-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_subscription_delete_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='follower',
            new_name='followers',
        ),
    ]
