# Generated by Django 5.1.2 on 2024-10-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_rename_follower_subscription_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='followers',
            new_name='follower',
        ),
    ]
