# Generated by Django 5.1.2 on 2024-10-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Titre par défaut', max_length=255),
            preserve_default=False,
        ),
    ]
